### PR TITLE
Bump Kotest

### PR DESCRIPTION
**Pull request by aballano**

### CODE REVIEW

**Comment by 1Jajen1** [comment]
@aballano thanks for updating this^^

Mind if I push a few changes today or tomorrow? I'd like to change the module name and remove the api dependency on their property testing. Would like to not expose that if possible because the use case of the kotest module is being a testrunner for the arrow-check property tests. So re-exposing their prop tests seems like a bad idea^^
Probably still need it for the tests though.

**Comment by aballano** [comment]
@1Jajen1 Sure, any improvement is welcome 👍

**Comment by 1Jajen1** [comment]
Renamed the module and moved the deps around a bit to hide kotest from the api of these modules.

I hope this builds because I currently cannot build with local deps (something related to jvm targets and of course the android module...).

**Comment by rachelcarmena** [comment]
> I hope this builds because I currently cannot build with local deps (something related to jvm targets and of course the android module...).

Hi @1Jajen1 , sorry, it failed:

```
Unresolved reference: PropertySpec
```

Please, how can I help you? Could you provide more details about the errors with jvm targets? Thanks!!

**Pull request closed without merging**
