### PR TITLE
Unify configuration with the rest of Arrow libraries

### PR DESCRIPTION
**Pull request by rachelcarmena**
Good news @1Jajen1 !! The prettyprinter and the parser combinators don't have transitive dependencies about Arrow. I just reviewed the reason in prettyprinter and in that case Arrow is only being used to validate documentation so it's not necessary to exclude dependencies.

This is a PR on `update-arrow-0.10.5` branch. 

> The build will likely break because of the io changes, so when the config is done I can try and get that fixed^^

You can fix it on this branch (`centralized-conf`) before merging the PR.

When all the things are merged on master, I'll add the rest of missing GitHub actions.

Thanks @1Jajen1 !!!!

### CODE REVIEW

**Comment by rachelcarmena** [comment]
BTW, I saw some doubts about Gradle configuration (TODOs). I'll check it and fix it in another PR :+1:

**Comment by 1Jajen1** [comment]
Thanks :) But something seems a bit wrong. The build failed, as I'd expect, but it failed with "Caused by: java.lang.OutOfMemoryError: Java heap space" which I don't really understand.

> BTW, I saw some doubts about Gradle configuration (TODOs). I'll check it and fix it in another PR +1

Cool, thanks :) Specifically the part about having to include the maven repos for the prettyprinter and the parser is a bit annoying.

**Comment by rachelcarmena** [comment]
> Thanks :) But something seems a bit wrong. The build failed, as I'd expect, but it failed with "Caused by: java.lang.OutOfMemoryError: Java heap space" which I don't really understand.

Oh, I didn't have that problem. Let's see...

**Comment by rachelcarmena** [comment]
> > Thanks :) But something seems a bit wrong. The build failed, as I'd expect, but it failed with "Caused by: java.lang.OutOfMemoryError: Java heap space" which I don't really understand.
> 
> Oh, I didn't have that problem. Let's see...

It seems it was solved with https://github.com/arrow-kt/arrow-check/pull/9/commits/bce41a0ef4482c75d2045e10896eeaabcf54e3ac

**Comment by 1Jajen1** [comment]
Good thanks. I'll fix the io issues soon^^

**Comment by 1Jajen1** [comment]
I had to disable the import ordering rule. It enforces an import ordering that goes against the default which intellij uses. Apart from that this should be good to go.

**Comment by 1Jajen1** [comment]
I'll merge this if it builds in reasonable time again!

**Pull request merged**
