### PR TITLE
Try MonadTest instances without using extension

### PR DESCRIPTION
**Pull request by 1Jajen1**
Let's see if this helps..

From what I can tell the compiler still needs quite a bit of memory to work through this ~1.5GB locally (if I looked at the right thing :see_no_evil: ).
I know far too less about the kotlin compiler to judge why that may be the case...

### CODE REVIEW

**Comment by 1Jajen1** [comment]
And the answer is: Nope.
@rachelcarmena I don't frequently look at memory usage, is this exceedingly high even for arrow standarts or is this just a case of the ci simply having a small amount of memory available?
Also how would one look into what is causing this? I am a bit out of ideas apart from removing more `@extension` generated code, but that can't really be the issue.

**Comment by rachelcarmena** [comment]
> And the answer is: Nope.
> @rachelcarmena I don't frequently look at memory usage, is this exceedingly high even for arrow standarts or is this just a case of the ci simply having a small amount of memory available?
> Also how would one look into what is causing this? I am a bit out of ideas apart from removing more `@extension` generated code, but that can't really be the issue.

I've just added JAVA_OPTS :crossed_fingers:

**Comment by 1Jajen1** [comment]
Out of ideas and time for now. I'll play around with it later on...

**Comment by rachelcarmena** [comment]
> Out of ideas and time for now. I'll play around with it later on...

Thanks @1Jajen1!! No worries.  Let's continue in another moment! :raised_hands:

**Comment by 1Jajen1** [comment]
So after compiling current master locally and taking a look at what the compile process was doing I still have no idea, but maybe someone more familiar with the compilers internals has:
- First of it spends the last minute or so with spiking up gc activity to ~10% (pretty constant as well, so it either wasn't freeing much or there was too much allocation)
- The used heap was pretty constant towards the end, so who knows what might have caused it. All errors also indicate that this happens during codegen. So something in this code is excessive on the codegen part

So anyway I have dealt with neither compilers nor non-obvious memory leaks all that much, so any ideas are very welcome^^

So what is rather special about this code:
- It is very polymorphic (especially when looking at something stupid like `MonadTransDistributive` it might even seem excessive, I swear it's needed :see_no_evil: for `MonadTest` instances of anything other than `GenT`) :sweat_smile: 
- It (through kapt arrow-meta) has a ton of extension functions everywhere, I have lots of typeclass instances for pretty much every type because they are usually monad-transformers and thus get lots of instances just by lifting

Memory usage only really became a problem (at least locally for me) after I introduced all those instances (apart from the functor/applicative/monad stuff, that was there before). What crashed the compiler with out of memory before was adding `MonadDefer/Async/Concurrent` to `TestT`, which I then later removed. But as usual with these kinds of problems the exact cause is very hard to determine.

**Comment by 1Jajen1** [comment]
Some of the output:

**Comment by 1Jajen1** [comment]
Another interesting bit is that arrow (especially fx) uses way more memory to compile, yet the gc pauses aren't nearly as bad. It is also not nearly as spiky on cpu usage, more constant work... This is really weird...

**Comment by 1Jajen1** [comment]
Oh and this runs (and finishes) locally with `-Xmx1024m` (which I think is a default? At least visualvm shows that). That is even lower than what the java options on the ci imply. So yeah, this is getting weirder and weirder. Also quite frustrating as it compiles and runs all tests usually within 5 mins on my laptop.
So what is different:
- java version (ci: java 8, locally 11)
- env options (ci: Xms 512, Xmx 2048, locally Xmx 1024)
- os (ci: ubuntu, locally manjaro)

And likely different hardware: My laptop is a 3 year old dell xps 15 (dunno exact specs and can't be bothered to look them up now ^^)

@rachelcarmena Also something I just tested: The `JAVA_OPTS` do not apply to the kotlin compile process gradle starts! Might need that to be passed via other means will test some more^^

**Comment by nomisRev** [comment]
It's failing for me.

- OpenJDK Runtime Environment (Zulu 8.36.0.1-CA-macosx) (build 1.8.0_202-b05)
- Xmx 4,2GB Xms 256MB
- MacOs

EDIT: `./gradlew --no-daemon --no-build-cache --no-configure-on-demand --no-parallel clean build` it build correctly for me with this command.
It's a command I started using myself since last week on the Arrow project while working on Arrow Fx for local resource reasons, but it also results in a easier to reproduce builds and easier to decipher build logs.

**Comment by rachelcarmena** [comment]
Thanks @nomisRev !!!

@1Jajen1 , I also had a similar issue with an arrow library when forgetting to add this conf in `gradle.properties`:

```
org.gradle.jvmargs=-Xmx4g
org.gradle.parallel=true
kotlin.incremental=true
kotlintest.parallelism=1
```

However, I don't know which property is the most significant to solve the issue. I hope it's another thing to try!

**Comment by 1Jajen1** [comment]
@rachelcarmena Thanks, I'll try that tomorrow. If that does not work, I'll attempt a few shotgun approaches, like removing kapt generated classes for most of the code-base etc. If those don't work I'll continue with the project as is and wait for https://youtrack.jetbrains.com/issue/KT-36405 to maybe get some answers...

**Comment by 1Jajen1** [comment]
So that did it. Removing `@extension` everywhere makes this code compile in good time! I'll reenable this later when this can use arrow-meta instead but for now this seems to work!

**Comment by 1Jajen1** [comment]
This brings me to the conclusion that kapt + `@extension` puts huge pressure on codegen. Interesting because `arrow-fx-mtl` suffers from this as well. Either way this will be a good test for arrow-meta in terms of performance regarding this specific problem^^

**Comment by rachelcarmena** [comment]
Thanks @1Jajen1 and congrats! :tada: Let's change this pull request to "ready for review" in order to integrate it and let's create an issue to work on it later.

**Review by rachelcarmena — APPROVED** [review]

**Comment by 1Jajen1** [comment]
I'll give this a quick review, update the youtrack issue and create one here after that :+1:

**Comment by 1Jajen1** [comment]
I'll also at some point try to incrementally enable those again, but I don't really want to work on this anymore in the near future :sweat_smile:

**Pull request merged**
